const constants = {
    HIDE_SIDEBAR: "HIDE_SIDEBAR",
    FETCH_INITIAL_DATA: "FETCH_INITIAL_DATA",
    FETCH_CONTENTS: "FETCH_INITIAL_CONTENTS",
    FOLD_CATEGORY: "FORD_CATEGORY"
}

export default constants