const constants = {
    HIDE_SIDEBAR: "HIDE_SIDEBAR",
    HIDE_NOTICE: "HIDE_SIDEBAR",
    ADD_CATEGORY: "ADD_CATEGORY",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    ADD_WRITING: "ADD_WRITING",
    FETCH_WRITINGS: "FETCH_WRITINGS"
}

export default constants